apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-backend-deployment
  labels:
    app: devops-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-backend
  template:
    metadata:
      labels:
        app: devops-backend
    spec:
      containers:
        - name: devops-backend
          image: swapie2212/devops-demo:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.devops.svc.cluster.local:3306/devopsdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root